### ISSUE TITLE
Navigation System Should Only Use Nautical Miles

### ISSUE THREAD

**Issue by decaff42** [YSCEDC/YSCE#12]
Currently the VOR system on the HUD uses Nautical Miles, but the navigation menu uses statute miles. This causes confusion and a single unit should be used. since Nautical Miles are used for real navigation, we should update the navigation menu distances to be Nautical miles.

**Comment by Skipper-is** [comment]
Yea, that should be easily doable. I'll assign myself and get it done.

**Comment by NodokaHanamura** [comment]
Issue has been resolved as of skipper's PR.
