### ISSUE TITLE
[BUG] F3 targets dead aircraft

### ISSUE THREAD

**Issue by NodokaHanamura** [YSCEDC/YSCE#38]
**YSCE Build Number**
Upstream 

**System Specifications**
Operating System: Windows 10
CPU: AMD Ryzen 5 3600 
GPU: NVIDIA RTX 3060
RAM: DDR4 32GB

**Describe the bug**
F3 Aircraft View mode will sometimes default back to F1 after attempting to view an aircraft that is no longer in the simulation.

**To Reproduce**
1. Create a Air Combat mission, preferably on Aomori. 
2. Launch and shoot down aircraft. 
3. Cycle through F3 Targets. 

**Expected behavior**
Destroyed aircraft should not be referenced by the F3 view. 

**Screenshots**
N/A

**Additional context**
Found this issue in @JOBBIN9422's dogfight rework build, though AFAIK we haven't touched the F3 view code.

**Comment by pasutisu** [comment]
@NodokaHanamura 
I have pushed pull req ( #39 ) for this issue.
