### ISSUE TITLE
[FEATURE] Ability to turn off and on messages liked "Locked On"

### ISSUE THREAD

**Issue by decaff42** [YSCEDC/YSCE#41]
When trying to get clear screenshots, sometimes there are messages that appear like "!! YOU ARE LOCKED ON!!", "!!MISSILE!!", "STALL", "!!!!    Overrun    !!!!", "!!!!UNPAVED FIELD!!!!", "TAIL STRIKE!!" etc that are hard coded into the middle of the screen which make it impossible to get good screenshots sometimes. These appear even in the F10 Ghost View

I think that messages like this should be either suppressed in F10 ghost view or something that can be toggled in the in-game CTRL menu.

**Comment by NodokaHanamura** [comment]
Resolved with PR #45.
