### ISSUE TITLE
Ground texture cannot be disabled

### ISSUE THREAD

**Issue by app4soft** [YSCEDC/YSCE#8]
- **YSFlight version:** `20181124` (AFFECTED), `20150425` (NOT affected)
- **YSCE version:** `master` (AFFECTED)
- **Platform/OS:** Linux (Debian 11)

### Actual behavior

Ground texture still shown even disable it via *"Option > Config > OpenGL > Use Ground Texture"*.

### Expected behavior

If *"Option > Config > OpenGL > Use Ground Texture"* is disabled (unchecked) ground textures should not be shown.

**Comment by NodokaHanamura** [comment]
Bringing this back from the grave, anyone wanna see about tackling this?

**Comment by JOBBIN9422** [comment]
![Untitled](https://github.com/YSCEDC/YSCE/assets/32369412/fc7c6942-9cac-4ad0-857b-906b82af7dad)

is this the expected appearance when "Use Ground Texture" is disabled in the OpenGL config menu?

**Comment by JOBBIN9422** [comment]
@NodokaHanamura good to close this one?

**Comment by NodokaHanamura** [comment]
Completely forgot. Closing now.
