### ISSUE TITLE
Add more types of weapon

### ISSUE THREAD

**Issue by app4soft** [YSCEDC/YSCE#9]
### Expected behavior

Add more types of weapon

### REFERENCE 

- https://github.com/pasutisu/YSFLIGHT/tree/dev/add-weapon

**Comment by NodokaHanamura** [comment]
This is planned to be done in the future, we are currently focused on documenting code and making small changes for the time being.

Thanks regardless for your feedback.

**Comment by NodokaHanamura** [comment]
Fixing the status of it. Don't worry, we will come back to this.
